package com.saga.be.entity.enums;

public enum AiEvidenceType {
	COMMIT_MESSAGE, TASK_FIELD, METADATA, EXCLUSION_MANIFEST, CHANGED_FILE_MANIFEST, PROVIDER_EVIDENCE_STATUS, DIFF_HUNK, CODE_RANGE, TEST_RESULT, CI_RESULT, SYLLABUS_NODE, HUMAN_CONFIRMED_EXAMPLE
}
