package com.saga.be.entity.enums;

public enum AttributionRiskSignal {
	EXTERNAL_IDENTITY_ALREADY_CLAIMED,
	IDENTITY_CHANGED_NEAR_DEADLINE,
	IDENTITY_RELINKED_AFTER_CONTRIBUTION,
	JIRA_ASSIGNEE_GITHUB_ACTOR_MISMATCH,
	PROVIDER_ACTIVITY_WITHOUT_SAGA_TASK_EVIDENCE,
	UNMAPPED_PROVIDER_IDENTITY,
	CONTRIBUTION_CONFIRMATION_MISSING,
	UNUSUAL_ACTIVITY_PATTERN,
	WEBHOOK_OR_INTEGRATION_SECURITY_FAILURE
}
