package com.saga.be.service.ai;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.saga.be.ai.*;
import java.util.*;
import org.junit.jupiter.api.Test;

class AiAcademicResultValidatorTest {
 private final AiAcademicResultValidator validator=new AiAcademicResultValidator(new ObjectMapper());
 private final UUID syllabus=UUID.randomUUID(),phaseA=UUID.randomUUID(),phaseB=UUID.randomUUID(),deliverable=UUID.randomUUID(),artifact=UUID.randomUUID(),phaseEvidence=UUID.randomUUID(),phaseBEvidence=UUID.randomUUID(),deliverableEvidence=UUID.randomUUID(),syllabusEvidence=UUID.randomUUID();
 @Test void acceptsPhaseDeliverableAndMultipleDistinctProposals() { assertThat(validator.invalidReason(proposed(row("PHASE",phaseA,.5,List.of(artifact,phaseEvidence))),evidence("COMPLETE"))).isEmpty();assertThat(validator.invalidReason(proposed(row("EXPECTED_DELIVERABLE",deliverable,.5,List.of(artifact,deliverableEvidence))),evidence("COMPLETE"))).isEmpty();assertThat(validator.invalidReason(proposed(row("PHASE",phaseA,.5,List.of(artifact,phaseEvidence)),row("EXPECTED_DELIVERABLE",deliverable,.5,List.of(artifact,deliverableEvidence))),evidence("COMPLETE"))).isEmpty(); }
 @Test void acceptsBothAbstentionDecisionsOnlyWhenEmpty() { assertThat(validator.invalidReason(result(AiAcademicClassificationDecision.UNCLASSIFIED,List.of(),true),evidence("COMPLETE"))).isEmpty();assertThat(validator.invalidReason(result(AiAcademicClassificationDecision.INSUFFICIENT_EVIDENCE,List.of(),true),evidence("COMPLETE"))).isEmpty(); }
 @Test void rejectsInvalidTargetsAndContext() { assertInvalid(proposed(row("PHASE",UUID.randomUUID(),.5,List.of(artifact,phaseEvidence))),evidence("COMPLETE"));assertInvalid(proposed(row("LEARNING_OUTCOME",phaseA,.5,List.of(artifact,phaseEvidence))),evidence("COMPLETE"));assertInvalid(proposed(row("LEARNING_UNIT",phaseA,.5,List.of(artifact,phaseEvidence))),evidence("COMPLETE"));assertInvalid(proposed(row("CAPABILITY",phaseA,.5,List.of(artifact,phaseEvidence))),evidence("COMPLETE"));assertInvalid(proposed(row("PROJECT_TYPE",phaseA,.5,List.of(artifact,phaseEvidence))),evidence("COMPLETE"));assertInvalid(proposed(row("PHASE",phaseA,.5,List.of(artifact,phaseEvidence))),evidenceWithOtherSyllabus()); }
 @Test void rejectsDuplicateBadConfidenceAndDecisionViolations() { assertInvalid(proposed(row("PHASE",phaseA,.5,List.of(artifact,phaseEvidence)),row("PHASE",phaseA,.6,List.of(artifact,phaseEvidence))),evidence("COMPLETE"));assertInvalid(proposed(row("PHASE",phaseA,1.1,List.of(artifact,phaseEvidence))),evidence("COMPLETE"));assertInvalid(proposed(row("PHASE",phaseA,-.1,List.of(artifact,phaseEvidence))),evidence("COMPLETE"));assertInvalid(result(AiAcademicClassificationDecision.PROPOSED,List.of(),true),evidence("COMPLETE"));assertInvalid(result(AiAcademicClassificationDecision.UNCLASSIFIED,List.of(row("PHASE",phaseA,.5,List.of(artifact,phaseEvidence))),true),evidence("COMPLETE"));assertInvalid(result(AiAcademicClassificationDecision.INSUFFICIENT_EVIDENCE,List.of(row("PHASE",phaseA,.5,List.of(artifact,phaseEvidence))),true),evidence("COMPLETE"));assertInvalid(result(AiAcademicClassificationDecision.PROPOSED,List.of(row("PHASE",phaseA,.5,List.of(artifact,phaseEvidence))),false),evidence("COMPLETE")); }
 @Test void rejectsUnknownForeignAndInsufficientEvidenceReferences() { assertInvalid(proposed(row("PHASE",phaseA,.5,List.of(UUID.randomUUID(),phaseEvidence))),evidence("COMPLETE"));assertInvalid(proposed(row("PHASE",phaseA,.5,List.of(artifact,UUID.randomUUID()))),evidence("COMPLETE"));assertInvalid(proposed(row("PHASE",phaseA,.5,List.of())),evidence("COMPLETE"));assertInvalid(proposed(row("PHASE",phaseA,.5,List.of(phaseEvidence))),evidence("COMPLETE"));assertInvalid(proposed(row("PHASE",phaseA,.5,List.of(artifact))),evidence("COMPLETE"));assertInvalid(proposed(row("PHASE",phaseA,.5,List.of(artifact,phaseBEvidence))),evidence("COMPLETE")); }
 @Test void rejectsProposedResultWhenCandidateCatalogIsPartial() { assertInvalid(proposed(row("PHASE",phaseA,.5,List.of(artifact,phaseEvidence))),evidence("PARTIAL")); }
 private void assertInvalid(AiAcademicClassificationResult result,List<AiAnalysisRequest.AiEvidenceInput> evidence){assertThat(validator.invalidReason(result,evidence)).isPresent();}
 private AiAcademicClassificationResult proposed(AiAcademicProposedClassification... rows){return result(AiAcademicClassificationDecision.PROPOSED,List.of(rows),true);} private AiAcademicClassificationResult result(AiAcademicClassificationDecision decision,List<AiAcademicProposedClassification> rows,boolean review){return new AiAcademicClassificationResult(decision,rows,"summary",review);} private AiAcademicProposedClassification row(String type,UUID target,double confidence,List<UUID> refs){return new AiAcademicProposedClassification(type,target.toString(),confidence,"why",refs.stream().map(UUID::toString).toList());}
 private List<AiAnalysisRequest.AiEvidenceInput> evidence(String coverage){return List.of(input(artifact,"COMMIT_MESSAGE",Map.of("message","work")),input(syllabusEvidence,"SYLLABUS_VERSION",Map.of("syllabusVersionId",syllabus,"candidateContext",coverage)),input(phaseEvidence,"SYLLABUS_PHASE",Map.of("targetType","PHASE","targetId",phaseA,"syllabusVersionId",syllabus)),input(phaseBEvidence,"SYLLABUS_PHASE",Map.of("targetType","PHASE","targetId",phaseB,"syllabusVersionId",syllabus)),input(deliverableEvidence,"SYLLABUS_DELIVERABLE",Map.of("targetType","EXPECTED_DELIVERABLE","targetId",deliverable,"syllabusVersionId",syllabus)));}
 private List<AiAnalysisRequest.AiEvidenceInput> evidenceWithOtherSyllabus(){UUID other=UUID.randomUUID();return List.of(input(artifact,"COMMIT_MESSAGE",Map.of()),input(syllabusEvidence,"SYLLABUS_VERSION",Map.of("syllabusVersionId",syllabus,"candidateContext","COMPLETE")),input(phaseEvidence,"SYLLABUS_PHASE",Map.of("targetType","PHASE","targetId",phaseA,"syllabusVersionId",other)));}
 private AiAnalysisRequest.AiEvidenceInput input(UUID id,String type,Map<String,Object> payload){try{return new AiAnalysisRequest.AiEvidenceInput(id,type,type, new ObjectMapper().writeValueAsString(payload),null);}catch(Exception ex){throw new AssertionError(ex);}}
}
