package com.saga.be.service.ai;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.saga.be.ai.*;
import com.saga.be.entity.academic.*;
import com.saga.be.entity.ai.*;
import com.saga.be.entity.enums.*;
import com.saga.be.entity.project.Project;
import com.saga.be.repository.*;
import java.util.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.dao.DataIntegrityViolationException;

class AiAcademicProposalFinalizationServiceTest {
 private AiAnalysisRunRepository runs; private AiAnalysisProviderDecisionRepository decisions; private AiAcademicClassificationRepository classifications; private SubjectSyllabusVersionRepository syllabuses; private SyllabusPhaseRepository phases; private SyllabusExpectedDeliverableRepository deliverables; private AiAcademicProposalFinalizationService service; private UUID runId,syllabusId,phaseId; private AiAnalysisStateService.ExecutionInput input;
 @BeforeEach void setUp() throws Exception {runs=mock(AiAnalysisRunRepository.class);decisions=mock(AiAnalysisProviderDecisionRepository.class);classifications=mock(AiAcademicClassificationRepository.class);syllabuses=mock(SubjectSyllabusVersionRepository.class);phases=mock(SyllabusPhaseRepository.class);deliverables=mock(SyllabusExpectedDeliverableRepository.class);service=new AiAcademicProposalFinalizationService(runs,decisions,classifications,syllabuses,phases,deliverables,new ObjectMapper());runId=UUID.randomUUID();syllabusId=UUID.randomUUID();phaseId=UUID.randomUUID();Project project=new Project();project.setId(UUID.randomUUID());AiAnalysisRun run=new AiAnalysisRun();run.setId(runId);run.setProject(project);run.setArtifactType(AiArtifactType.COMMIT);run.setArtifactId(UUID.randomUUID());run.setArtifactRevision("exact-sha");AiAnalysisProviderDecision decision=new AiAnalysisProviderDecision();input=new AiAnalysisStateService.ExecutionInput(run,List.of(evidence(AiEvidenceType.SYLLABUS_VERSION,Map.of("syllabusVersionId",syllabusId),Map.of("syllabusVersionId",syllabusId,"candidateContext","COMPLETE")),evidence(AiEvidenceType.SYLLABUS_PHASE,Map.of("targetType","PHASE","targetId",phaseId,"syllabusVersionId",syllabusId),null)),decision);when(runs.completeRunning(eq(runId),any())).thenReturn(1);when(decisions.completeRunning(eq(runId),anyString(),eq(true),any(),any(),any(),any(),any(),any())).thenReturn(1);SubjectSyllabusVersion syllabus=new SubjectSyllabusVersion();syllabus.setId(syllabusId);when(syllabuses.findById(syllabusId)).thenReturn(Optional.of(syllabus));SyllabusPhase phase=new SyllabusPhase();phase.setId(phaseId);phase.setSyllabusVersionId(syllabusId);when(phases.findById(phaseId)).thenReturn(Optional.of(phase));}
 @Test void proposedRowsUseRunIdentityAndValidatedCandidateTarget() { assertThat(service.finalize(input,response(AiAcademicClassificationDecision.PROPOSED,List.of(proposal())),"{\"valid\":true}")).isTrue(); @SuppressWarnings("unchecked") var rows=(Iterable<AiAcademicClassification>)mockingDetails(classifications).getInvocations().stream().filter(i->i.getMethod().getName().equals("saveAllAndFlush")).findFirst().orElseThrow().getArgument(0);AiAcademicClassification row=rows.iterator().next();assertThat(row.getProject()).isSameAs(input.run().getProject());assertThat(row.getArtifactRevision()).isEqualTo("exact-sha");assertThat(row.getSyllabusVersion().getId()).isEqualTo(syllabusId);assertThat(row.getPhase().getId()).isEqualTo(phaseId);assertThat(row.getProvenance()).isEqualTo(AiAcademicProvenance.AI);assertThat(row.getStatus()).isEqualTo(AiAcademicClassificationStatus.PROPOSED);verify(decisions).completeRunning(eq(runId),eq("{\"valid\":true}"),eq(true),any(),any(),any(),any(),any(),any()); }
 @Test void unclassifiedAndInsufficientEvidenceCompleteWithoutProposalRows() { assertThat(service.finalize(input,response(AiAcademicClassificationDecision.UNCLASSIFIED,List.of()),"{} ")).isTrue();verifyNoInteractions(classifications); }
 @Test void lateResultCasWritesNeitherDecisionNorProposal() { when(runs.completeRunning(eq(runId),any())).thenReturn(0);assertThat(service.finalize(input,response(AiAcademicClassificationDecision.PROPOSED,List.of(proposal())),"{}")).isFalse();verifyNoInteractions(decisions,classifications); }
 @Test void proposalPersistenceFailureEscapesTheTransactionRatherThanCompletingPartially() { doThrow(new DataIntegrityViolationException("forced")).when(classifications).saveAllAndFlush(any());assertThatThrownBy(()->service.finalize(input,response(AiAcademicClassificationDecision.PROPOSED,List.of(proposal())),"{}")).isInstanceOf(DataIntegrityViolationException.class);verify(runs).completeRunning(eq(runId),any());verify(decisions).completeRunning(eq(runId),anyString(),eq(true),any(),any(),any(),any(),any(),any()); }
 private AiProviderResponse response(AiAcademicClassificationDecision decision,List<AiAcademicProposedClassification> rows){return new AiProviderResponse(new AiAcademicClassificationResult(decision,rows,"summary",true),1L,2L,3L,"model",null);}private AiAcademicProposedClassification proposal(){return new AiAcademicProposedClassification("PHASE",phaseId.toString(),.8,"summary",List.of());} private AiAnalysisEvidence evidence(AiEvidenceType type,Map<String,Object> payload,Map<String,Object> metadata)throws Exception{AiAnalysisEvidence row=new AiAnalysisEvidence();row.setId(UUID.randomUUID());row.setEvidenceType(type);row.setPayloadJson(new ObjectMapper().writeValueAsString(payload));row.setMetadataJson(metadata==null?null:new ObjectMapper().writeValueAsString(metadata));return row;}
}
