package com.saga.be.service.ai;
import com.saga.be.entity.academic.*; import com.saga.be.entity.account.UserAccount; import com.saga.be.entity.ai.*; import com.saga.be.entity.enums.*; import com.saga.be.exception.IntegrationException; import com.saga.be.integration.IntegrationErrorCode; import com.saga.be.repository.*; import java.time.LocalDateTime; import java.util.UUID; import org.springframework.context.annotation.Profile; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
/** One conditional PROPOSED->terminal transition plus one append-only review record. */
@Service @Profile("!test") public class AiAcademicReviewService {
 private final AiAcademicClassificationRepository classifications; private final AiAcademicClassificationReviewRepository reviews; private final UserAccountRepository users; private final ProjectRepository projects; private final SyllabusPhaseRepository phases; private final SyllabusExpectedDeliverableRepository deliverables;
 public AiAcademicReviewService(AiAcademicClassificationRepository c,AiAcademicClassificationReviewRepository r,UserAccountRepository u,ProjectRepository p,SyllabusPhaseRepository ph,SyllabusExpectedDeliverableRepository d){classifications=c;reviews=r;users=u;projects=p;phases=ph;deliverables=d;}
 @Transactional public AiAcademicClassification review(UUID actor,UUID projectId,UUID id,Request request){ requireLecturer(actor,projectId); AiAcademicClassification proposal=classifications.findById(id).filter(c->c.getProject().getId().equals(projectId)&&c.getProvenance()==AiAcademicProvenance.AI).orElseThrow(()->notFound()); if(request.action()==AiAcademicReviewAction.REJECT||request.action()==AiAcademicReviewAction.CORRECT){if(request.reason()==null||request.reason().isBlank()) throw invalid("Reason is required.");} if(request.action()!=AiAcademicReviewAction.CORRECT&&(request.correctedTargetType()!=null||request.correctedTargetId()!=null)) throw invalid("Correction target is only valid for CORRECT."); AiAcademicClassificationStatus terminal=request.action()==AiAcademicReviewAction.CONFIRM?AiAcademicClassificationStatus.CONFIRMED:request.action()==AiAcademicReviewAction.REJECT?AiAcademicClassificationStatus.REJECTED:AiAcademicClassificationStatus.CORRECTED; if(classifications.terminalReview(id,terminal)!=1) throw new IntegrationException(IntegrationErrorCode.INTEGRATION_UNAVAILABLE,HttpStatus.CONFLICT,"Academic proposal was already reviewed."); UserAccount reviewer=users.findById(actor).orElseThrow(); AiAcademicClassificationReview review=new AiAcademicClassificationReview(); review.setClassification(proposal);review.setAction(request.action());review.setReviewer(reviewer);review.setReason(request.reason()); if(request.action()==AiAcademicReviewAction.CORRECT){ Target t=target(proposal.getSyllabusVersion().getId(),request.correctedTargetType(),request.correctedTargetId()); review.setCorrectedTargetType(t.type);review.setCorrectedPhase(t.phase);review.setCorrectedDeliverable(t.deliverable); AiAcademicClassification human=new AiAcademicClassification(); human.setProject(proposal.getProject());human.setAnalysisRun(proposal.getAnalysisRun());human.setArtifactType(proposal.getArtifactType());human.setArtifactId(proposal.getArtifactId());human.setArtifactRevision(proposal.getArtifactRevision());human.setSyllabusVersion(proposal.getSyllabusVersion());human.setTargetType(t.type);human.setPhase(t.phase);human.setDeliverable(t.deliverable);human.setConfidence(1d);human.setAiSummary(request.reason());human.setStatus(AiAcademicClassificationStatus.CONFIRMED);human.setProvenance(AiAcademicProvenance.HUMAN);human.setSourceClassification(proposal);human.setReviewedAt(LocalDateTime.now());classifications.save(human); } reviews.save(review); return proposal; }
 private Target target(UUID version,AiAcademicTargetType type,UUID id){if(type==null||id==null)throw invalid("Correction target is required."); if(type==AiAcademicTargetType.PHASE){SyllabusPhase p=phases.findById(id).filter(x->version.equals(x.getSyllabusVersionId())).orElseThrow(()->invalid("Phase is not in the pinned syllabus."));return new Target(type,p,null);} SyllabusExpectedDeliverable d=deliverables.findById(id).filter(x->version.equals(x.getSyllabusVersionId())).orElseThrow(()->invalid("Deliverable is not in the pinned syllabus."));return new Target(type,null,d);}
 private void requireLecturer(UUID user,UUID project){UserAccount a=users.findById(user).orElseThrow();if(a.getAccountRole()!=AccountRole.LECTURER||!projects.existsAssignedToLecturerUser(project,user))throw new IntegrationException(IntegrationErrorCode.ACCESS_DENIED,HttpStatus.FORBIDDEN,"Assigned lecturer access is required.");}
 private static IntegrationException notFound(){return new IntegrationException(IntegrationErrorCode.AI_ANALYSIS_NOT_FOUND,HttpStatus.NOT_FOUND,"Academic classification was not found.");} private static IntegrationException invalid(String s){return new IntegrationException(IntegrationErrorCode.AI_ANALYSIS_RESULT_INVALID,HttpStatus.BAD_REQUEST,s);} private record Target(AiAcademicTargetType type,SyllabusPhase phase,SyllabusExpectedDeliverable deliverable){} public record Request(AiAcademicReviewAction action,String reason,AiAcademicTargetType correctedTargetType,UUID correctedTargetId){}
}
