package com.saga.be.service.ai;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.*;
import com.saga.be.ai.*;
import com.saga.be.config.AiAnalysisProperties;
import com.saga.be.entity.enums.*;
import java.util.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.condition.ConditionalOnExpression;
import org.springframework.context.annotation.Profile;
import org.springframework.http.MediaType;
import org.springframework.http.client.SimpleClientHttpRequestFactory;
import org.springframework.stereotype.Component;
import org.springframework.web.client.*;

/** Internal saga-ai inference adapter; domain validation and state authority stay in saga-be. */
@Component @Profile("!test & !local") @ConditionalOnExpression("'${saga.ai.enabled:false}' == 'true' and '${saga.ai.primary-provider:openai}' == 'remote'")
public class RemoteAiModelProvider implements AiModelProvider {
 static final String CONTRACT="saga-ai-inference-v1"; private final AiAnalysisProperties props;private final ObjectMapper mapper;private final RestClient client;
 @Autowired public RemoteAiModelProvider(AiAnalysisProperties p,ObjectMapper m){this(p,m,client(p));} RemoteAiModelProvider(AiAnalysisProperties p,ObjectMapper m,RestClient c){props=p;mapper=m;client=c;}
 private static RestClient client(AiAnalysisProperties p){SimpleClientHttpRequestFactory factory=new SimpleClientHttpRequestFactory();factory.setConnectTimeout(p.getRuntime().getTimeout());factory.setReadTimeout(p.getRuntime().getTimeout());return RestClient.builder().baseUrl(p.getRuntime().getBaseUrl()).requestFactory(factory).build();}
 public AiProviderRole role(){return AiProviderRole.PRIMARY;} public String providerKey(){return "saga-ai";} public String providerConfigHash(){return AiHashes.sha256("saga-ai|"+props.getRuntime().getBaseUrl()+"|"+props.getOpenai().getModel()+"|"+props.getOpenai().getReasoningEffort()+"|"+CONTRACT);} public String modelId(){return props.getOpenai().getModel();}
 public AiProviderResponse analyze(AiAnalysisRequest request){if(!props.getRuntime().isEnabled()||blank(props.getRuntime().getBaseUrl())||blank(props.getRuntime().getInternalToken()))throw new AiProviderException("AI_RUNTIME_NOT_CONFIGURED");String id=request.runId()+":"+request.providerRole();try{Map<String,Object> body=new LinkedHashMap<>();body.put("requestId",id);body.put("analysisType",request.analysisType().name());body.put("contractVersion",CONTRACT);body.put("promptVersion",request.promptVersion());body.put("taxonomyVersion",request.taxonomyVersion());body.put("provider",Map.of("role",request.providerRole().name(),"model",modelId(),"reasoningEffort",props.getOpenai().getReasoningEffort()));List<Object> evidence=new ArrayList<>();for(var e:request.evidence())evidence.add(Map.of("id",e.id().toString(),"type",e.type(),"sourceRef",e.sourceRef(),"payload",json(e.payloadJson()),"metadata",e.metadataJson()==null?Map.of():json(e.metadataJson())));body.put("evidence",evidence);body.put("context",Map.of());String responseBody=client.post().uri("/internal/v1/analyses").contentType(MediaType.APPLICATION_JSON).header("Authorization","Bearer "+props.getRuntime().getInternalToken()).body(body).retrieve().body(String.class);JsonNode response=mapper.readTree(responseBody);if(response==null||!id.equals(response.path("requestId").asText())||!request.analysisType().name().equals(response.path("analysisType").asText())||!CONTRACT.equals(response.path("contractVersion").asText()))throw new AiProviderException("AI_PROVIDER_RESULT_INVALID");JsonNode result=response.path("result");if(!request.analysisType().name().equals(result.path("kind").asText()))throw new AiProviderException("AI_PROVIDER_RESULT_INVALID");AiAnalysisResult mapped=request.analysisType()==AiAnalysisType.COMMIT_INTELLIGENCE?mapper.treeToValue(result.path("payload"),AiStructuredResult.class):mapper.treeToValue(result.path("payload"),AiAcademicClassificationResult.class);JsonNode usage=response.path("usage"),provider=response.path("provider");return new AiProviderResponse(mapped,usage.path("latencyMs").isMissingNode()?null:usage.path("latencyMs").asLong(),usage.path("inputUnits").isMissingNode()?null:usage.path("inputUnits").asLong(),usage.path("outputUnits").isMissingNode()?null:usage.path("outputUnits").asLong(),provider.path("modelRevision").asText(null),mapper.writeValueAsString(Map.of("responseId",provider.path("responseId").asText(""),"providerKey",provider.path("providerKey").asText(""),"modelId",provider.path("modelId").asText(""))));}catch(AiProviderException e){throw e;}catch(RestClientResponseException e){throw new AiProviderException(remoteCode(e));}catch(RestClientException e){throw new AiProviderException("AI_PROVIDER_TIMEOUT");}catch(Exception e){throw new AiProviderException("AI_PROVIDER_RESULT_INVALID",e);}}
 private String remoteCode(RestClientResponseException e){try{String code=mapper.readTree(e.getResponseBodyAsString()).path("error").path("code").asText();if(Set.of("AI_RUNTIME_NOT_CONFIGURED","AI_RUNTIME_DISABLED","AI_RUNTIME_UNAVAILABLE","AI_PROVIDER_AUTH_FAILED","AI_PROVIDER_RATE_LIMITED","AI_PROVIDER_TIMEOUT","AI_PROVIDER_FAILED","AI_PROVIDER_RESULT_INVALID","AI_CONTRACT_VERSION_UNSUPPORTED").contains(code))return code;}catch(Exception ignored){}int s=e.getStatusCode().value();return s==401?"AI_RUNTIME_UNAVAILABLE":s==429?"AI_PROVIDER_RATE_LIMITED":"AI_PROVIDER_FAILED";}
 private Map<String,Object> json(String raw)throws Exception{return mapper.readValue(raw,new TypeReference<Map<String,Object>>(){});}private static boolean blank(String s){return s==null||s.isBlank();}
}
