package com.saga.be.auth;

public enum AuthErrorCode {
	INVALID_CREDENTIALS,
	ACCOUNT_DISABLED,
	GOOGLE_EMAIL_NOT_VERIFIED,
	GOOGLE_DOMAIN_NOT_ALLOWED,
	GOOGLE_IDENTITY_CONFLICT,
	GOOGLE_ACCOUNT_NOT_ELIGIBLE,
	PASSWORD_SETUP_REQUIRED,
	PASSWORD_ALREADY_SET,
	PASSWORD_POLICY_VIOLATION,
	PASSWORD_CONFIRMATION_MISMATCH,
	EMAIL_ALREADY_REGISTERED,
	INSTITUTIONAL_EMAIL_USE_GOOGLE,
	STUDENT_CODE_ALREADY_EXISTS,
	INVALID_REGISTRATION_DATA
}
