package com.saga.be.integration;

public enum IntegrationErrorCode {
	OAUTH_STATE_INVALID,
	OAUTH_STATE_EXPIRED,
	EXTERNAL_IDENTITY_ALREADY_LINKED,
	EXTERNAL_IDENTITY_NOT_FOUND,
	INTEGRATION_FORBIDDEN,
	NOT_TEAM_LEADER,
	GITHUB_INSTALLATION_INVALID,
	GITHUB_INSTALLATION_NOT_AUTHORIZED,
	GITHUB_REPOSITORY_NOT_ACCESSIBLE,
	JIRA_ACCOUNT_NOT_LINKED_TO_CURRENT_USER,
	JIRA_SITE_NOT_ACCESSIBLE,
	JIRA_PROJECT_NOT_ACCESSIBLE,
	JIRA_BOARD_NOT_ACCESSIBLE,
	JIRA_TOKEN_REFRESH_FAILED,
	WEBHOOK_SIGNATURE_INVALID,
	WEBHOOK_DUPLICATE,
	INTEGRATION_REVOKED,
	INTEGRATION_UNAVAILABLE,
	STEP_UP_REQUIRED,
	STEP_UP_EXPIRED,
	REAUTH_RATE_LIMITED,
	WEBAUTHN_DISABLED
}
