CREATE TABLE ai_academic_classification (
    id CHAR(36) NOT NULL,
    project_id CHAR(36) NOT NULL,
    analysis_run_id CHAR(36) NOT NULL,
    artifact_type VARCHAR(32) NOT NULL,
    artifact_id CHAR(36) NOT NULL,
    artifact_revision VARCHAR(128) NOT NULL,
    syllabus_version_id CHAR(36) NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    phase_id CHAR(36) NULL,
    deliverable_id CHAR(36) NULL,
    confidence DOUBLE NOT NULL,
    ai_summary TEXT NULL,
    status VARCHAR(32) NOT NULL,
    provenance VARCHAR(32) NOT NULL,
    source_classification_id CHAR(36) NULL,
    reviewed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_academic_classification_analysis_phase (analysis_run_id, phase_id),
    UNIQUE KEY uk_ai_academic_classification_analysis_deliverable (analysis_run_id, deliverable_id),
    KEY ix_ai_academic_classification_artifact (project_id, artifact_type, artifact_id, artifact_revision),
    KEY ix_ai_academic_classification_authoritative (project_id, artifact_type, artifact_id, artifact_revision, status, provenance),
    CONSTRAINT fk_ai_academic_classification_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT fk_ai_academic_classification_run FOREIGN KEY (analysis_run_id) REFERENCES ai_analysis_run(id),
    CONSTRAINT fk_ai_academic_classification_source FOREIGN KEY (source_classification_id) REFERENCES ai_academic_classification(id),
    CONSTRAINT fk_ai_academic_classification_syllabus FOREIGN KEY (syllabus_version_id) REFERENCES subject_syllabus_version(id),
    CONSTRAINT fk_ai_academic_classification_phase FOREIGN KEY (phase_id) REFERENCES syllabus_phase(id),
    CONSTRAINT fk_ai_academic_classification_deliverable FOREIGN KEY (deliverable_id) REFERENCES syllabus_expected_deliverable(id),
    CONSTRAINT ck_ai_academic_classification_target CHECK ((target_type = 'PHASE' AND phase_id IS NOT NULL AND deliverable_id IS NULL) OR (target_type = 'EXPECTED_DELIVERABLE' AND phase_id IS NULL AND deliverable_id IS NOT NULL)),
    CONSTRAINT ck_ai_academic_classification_confidence CHECK (confidence >= 0 AND confidence <= 1),
    CONSTRAINT ck_ai_academic_classification_provenance CHECK ((provenance = 'AI' AND source_classification_id IS NULL) OR (provenance = 'HUMAN' AND source_classification_id IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ai_academic_classification_review (
    id CHAR(36) NOT NULL,
    classification_id CHAR(36) NOT NULL,
    action VARCHAR(32) NOT NULL,
    reviewer_user_id CHAR(36) NOT NULL,
    reason TEXT NULL,
    corrected_target_type VARCHAR(32) NULL,
    corrected_phase_id CHAR(36) NULL,
    corrected_deliverable_id CHAR(36) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_academic_classification_review_once (classification_id),
    CONSTRAINT fk_ai_academic_review_classification FOREIGN KEY (classification_id) REFERENCES ai_academic_classification(id),
    CONSTRAINT fk_ai_academic_review_reviewer FOREIGN KEY (reviewer_user_id) REFERENCES user_account(id),
    CONSTRAINT fk_ai_academic_review_phase FOREIGN KEY (corrected_phase_id) REFERENCES syllabus_phase(id),
    CONSTRAINT fk_ai_academic_review_deliverable FOREIGN KEY (corrected_deliverable_id) REFERENCES syllabus_expected_deliverable(id),
    CONSTRAINT ck_ai_academic_review_correction CHECK ((action IN ('CONFIRM','REJECT') AND corrected_target_type IS NULL AND corrected_phase_id IS NULL AND corrected_deliverable_id IS NULL) OR (action = 'CORRECT' AND ((corrected_target_type = 'PHASE' AND corrected_phase_id IS NOT NULL AND corrected_deliverable_id IS NULL) OR (corrected_target_type = 'EXPECTED_DELIVERABLE' AND corrected_phase_id IS NULL AND corrected_deliverable_id IS NOT NULL))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
